baseURL = 'https://your-site-name.pages.dev/'
languageCode = 'zh-cn'
title = '咖啡时刻'
theme = 'cafe-moment'

[params]
  description = "探索咖啡的世界，分享咖啡师的故事和技艺"
  author = "咖啡师"
  github = "your-github-username"
  
  # 导航菜单
  [[params.menu]]
    name = "首页"
    url = "/"
    weight = 1
  
  [[params.menu]]
    name = "咖啡故事"
    url = "/stories/"
    weight = 2
  
  [[params.menu]]
    name = "咖啡知识"
    url = "/knowledge/"
    weight = 3
  
  [[params.menu]]
    name = "关于"
    url = "/about/"
    weight = 4

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  
  [[menu.main]]
    name = "咖啡故事"
    url = "/stories/"
    weight = 2
  
  [[menu.main]]
    name = "咖啡知识"
    url = "/knowledge/"
    weight = 3
  
  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[markup.highlight]
  style = "github"
  lineNos = true
  lineNumbersInTable = true

[markup.tableOfContents]
  endLevel = 3
  ordered = false
  startLevel = 1

[outputs]
  home = ["HTML", "RSS", "JSON"]

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[services]
  [services.googleAnalytics]
    id = ""

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = false

  [privacy.twitter]
    disabled = false
    simple = false

  [privacy.instagram]
    disabled = false
    simple = false

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series" 